image_pairs:
  - past_image: "602940"
    recent_image: "603169"
  - past_image: "602941"
    recent_image: "603170"
  - past_image: "602942"
    recent_image: "603171"
  - past_image: "602943"
    recent_image: "603172"
